name: PHP Checks
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: PHP syntax check
        run: |
          find . -type f -name "*.php" -print0 | xargs -0 -n1 php -l
